# 由当前机器的顶层 Homebrew 包维护；恢复前先安装 Homebrew。
# 更新时以 brew leaves / brew list --cask / mas list 为准。

# Taps
tap "bigwig-club/brew"
tap "darrylmorley/whatcable"
tap "domt4/autoupdate"
tap "homebrew/cask"
tap "homebrew/core"
tap "leaperone/smctl"
tap "romkatv/powerlevel10k"

# 顶层 formula；依赖由 Homebrew 自动解析。
brew "ack"
brew "ansible"
brew "aria2"
brew "asitop"
brew "aspell"
brew "ast-grep"
brew "astyle"
brew "atuin"
brew "autoenv"
brew "autojump"
brew "automake"
brew "awscli"
brew "bat"
brew "berkeley-db", link: true
brew "bison"
brew "boost-python3"
brew "btop"
brew "ccache"
brew "caddy"
brew "ceres-solver"
brew "cloc"
brew "cmake"
brew "commitizen"
brew "composer"
brew "cscope"
brew "ddrescue"
brew "difftastic"
brew "djvulibre"
brew "dlib"
brew "exiftool"
brew "eza"
brew "f3"
brew "fd"
brew "ffmpeg"
brew "fio"
brew "fping"
brew "frei0r"
brew "fzf"
brew "gawk"
brew "gemini-cli"
brew "gifsicle"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "glab"
brew "gnu-time"
brew "go"
brew "gobject-introspection"
brew "gping"
brew "graphviz"
brew "hf"
brew "htop"
brew "hyperfine"
brew "httping"
brew "iftop"
brew "imagemagick-full"
brew "immich-cli"
brew "ioping"
brew "iperf"
brew "iperf3"
brew "jc"
brew "jq"
brew "just"
brew "k6"
brew "kubernetes-cli"
brew "latexindent"
brew "leaperone/smctl/smctl"
brew "libbluray"
brew "libsoxr"
brew "linode-cli"
brew "lnav"
brew "mas"
brew "media-info"
brew "mediamtx"
brew "mkcert"
brew "minicom"
brew "mosh"
brew "mtr"
brew "mupdf"
brew "nasm"
brew "ncdu"
brew "ninja"
brew "nmap"
brew "ollama"
brew "opencore-amr"
brew "pandoc"
brew "parallel"
brew "pipx"
brew "pngpaste"
brew "pngquant"
brew "poppler"
brew "py3cairo"
brew "qpdf"
brew "rclone"
brew "redis"
brew "rename"
brew "repo"
brew "ripgrep"
brew "ripsecrets"
brew "rm-improved"
brew "rsync"
brew "rubberband"
brew "ruby"
brew "rustup"
brew "samba"
brew "scipy"
brew "screen"
brew "sd"
brew "shared-mime-info"
brew "smartmontools"
brew "snappy"
brew "sonar-scanner"
brew "speex"
brew "sshpass"
brew "srt"
brew "starship"
brew "stunnel"
brew "svg2pdf"
brew "svg2png"
brew "tcping"
brew "telnet"
brew "terminal-notifier"
brew "testdisk"
brew "theora"
brew "tlrc"
brew "tmux"
brew "topgrade"
brew "tokei"
brew "trippy"
brew "trufflehog"
brew "twoping"
brew "uv"
brew "vapoursynth"
brew "vim"
brew "virtualenv"
brew "wakeonlan"
brew "watch"
brew "wget"
brew "whisper-cpp"
brew "xvid"
brew "you-get"
brew "yq"
brew "yt-dlp"
brew "z"
brew "zoxide"
brew "zopfli"
brew "zsh"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Casks / 字体 / GUI 工具
cask "1password"
cask "1password-cli"
cask "adrive"
cask "android-platform-tools"
cask "anki"
cask "antigravity-cli"
cask "audacity"
cask "baidunetdisk"
cask "balenaetcher"
cask "bibdesk"
cask "calhash"
cask "calibre"
cask "codex-app"
cask "cyberduck"
cask "docker-desktop"
cask "drawio"
cask "feishu"
cask "focusrite-control"
cask "font-arial"
cask "font-fontawesome"
cask "font-maple-mono-nf-cn"
cask "ghostty"
cask "gpg-suite"
cask "hammerspoon"
cask "handbrake-app"
cask "iina"
cask "imageoptim"
cask "iterm2"
cask "libreoffice"
cask "localsend"
cask "maccy"
cask "macfuse"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "moonlight"
cask "obs"
cask "obsidian"
cask "ollama-app"
cask "packetsender"
cask "silicon-app"
cask "skim"
cask "spokenly"
cask "squirrel-app"
cask "synologyassistant"
cask "tailscale-app"
cask "teamviewer"
cask "telegram"
cask "tencent-meeting"
cask "topnotch"
cask "typeless"
cask "upic"
cask "veracrypt"
cask "visual-studio-code"
cask "vlc"
cask "whatcable"
cask "whatsapp"
cask "wireshark-app"
cask "xld"
cask "xquartz"
cask "zerotier-one"

# Mac App Store 应用
mas "Keynote", id: 409183694
mas "Blackmagic Disk Speed Test", id: 425264550
mas "The Unarchiver", id: 425424353
mas "GarageBand", id: 682658836
mas "DjVu Reader", id: 733144595
mas "TestFlight", id: 899247664
mas "BestTrace", id: 1037779758
mas "Home Assistant", id: 1099568401
mas "Speedtest", id: 1153157709
mas "Klib", id: 1196268448
mas "iMazing Converter", id: 1292198261
mas "Windows App", id: 1295203466
mas "Quantumult X", id: 1443988620
mas "Welly", id: 1521402269
mas "1Password for Safari", id: 1569813296
mas "Exif Editor", id: 1621435983
mas "APTV", id: 1630403500
